### ISSUE TITLE
Set mouse sensitivity

### ISSUE THREAD

**Issue by neeerp** [lujjjh/LinearMouse#15]
A nice feature would be if it were possible to also set the mouse sensitivity from LinearMouse preferences, ideally beyond the range provided in System Preferences.

For some context, I had previously used the SteerMouse free trial and it had the ability to set both mouse sensitivity and acceleration values (i.e. acceleration was on a range too) independently. I personally don't care for supporting acceleration besides on/off, but I think setting linear mouse sensitivity would be a great add here!

I'd also like to commend this project; glad there's a FOSS alternative to all this paid software for what should (in my opinion) be a default feature in MacOS! Great stuff!

**Comment by lujjjh** [comment]
Glad you like it!

Would be helpful if you could describe the scenario in which we need to set mouse sensitivity beyond the range provided in System Preferences.

Is the cursor speed still too slow / fast? Or perhaps you'd like to adjust the sensitivity to a more accurate value which exactly fits you?

**Comment by neeerp** [comment]
Sorry for not replying sooner, but yes, I find that the mouse sensitivity settings in System Preferences are insufficient for my needs... What you listed is pretty spot on.

* Cursor speeds are too slow even at the end of the given range
* Although it's possible to set cursor speed above the end of the range from the terminal, a reboot appears to be required to apply the settings which is extremely inconvenient and makes it hard to tune anything properly. 
* I'm also under the impression that past a certain scaling value, the manual setting doesn't increase the cursor speed (I'd set it to some absurd number just to test, but I can't reboot my machine at the time of writing this... lol).
* A numerical value that correctly reflects the current cursor speed would be great and is not provided by default (though you can read the value from the terminal, the issue from the previous point still stands.

**Comment by neeerp** [comment]
I tried to do a little bit of research yesterday and it seems what I'm asking for might not be easy to implement. I think it might be the case that this functionality would need to come as a kernel extension/driver. That seems to be how Steermouse and USB Overdrive accomplish that.

Granted, I know very little about MacOS so perhaps I'm wrong about this. I'm going to try looking into this more in my free time (if anything, just to learn a little bit about developing drivers). Given that I haven't been able to find any FOSS alternatives to Steermouse/USB Overdrive, I think actually managing to implement something like this would be much appreciated by more than just myself!

**Comment by lujjjh** [comment]
Cool! I'm also not sure how SteerMouse and USB Overdrive implement this function. I'll do some tests later.

Looking forward to your good news :)

**Comment by Saysano** [comment]
Hello, 

I second this request. To me, it's the opposite, it's too fast, I am used to having a lower sensitivity because I play a lot of FPS games. I also know very little about MacOS, I'm used to Windows. Nevertheless, thank you very much for the software, works like a charm. Having a way to choose the sensitivity of the cursor would be very appreciated !

**Comment by mreser99** [comment]
If this great app able to has own tracking speed settings that would be great. I'm using 1000dpi mouse and it seems slow. Because we can set mouse tracking speed under windows as our wish. I'm also setting under system preferences but it's reverting old setting a few seconds later.

**Comment by blubber** [comment]
I have this issue as well, using a magic mouse. When I enable linear mouse the tracking speed becomes way too fast. Moving the mouse a couple centimeters is enough to put the cursor on the other side of my display. I can set the tracking speed in the regular mouse preferences, but it gets reset to what I assume is it's fastest speed.

**Comment by lujjjh** [comment]
After several days' investigation, LinearMouse now supports cursor acceleration & sensitivity, which is greatly inspired by @noah-nuebling's [Mac Mouse Fix](https://github.com/noah-nuebling/mac-mouse-fix/blob/7a52439679ab242a891d0071443512b23f73dbe4/Helper/Pointer/PointerSpeed.m#L33).

To get an early access, download the binary [here](https://github.com/lujjjh/LinearMouse/actions/runs/1559050333). Any feedback could be helpful.

Currently you cannot set different values for different mice. I may support it in the future.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/3000535/145408182-98d07804-67a1-48a4-b976-e21a677ba435.png">

**Comment by coding-cucumber** [comment]
@lujjjh I tested it now, seems to work great. Note, I had to toggle accessibility permissions off then on again and restart the mac for it to work.

**Comment by lujjjh** [comment]
> [...] I had to toggle accessibility permissions off then on again and restart the mac for it to work.

@coding-cucumber Thank you for your test. Updates require regranting the permission; but toggling on and off without a reboot should work... I'll try to sign the app with a fixed certificate and see if this annoying issue could be solved.

**Comment by mreser99** [comment]
I've tested also and working great with logitech m185. Thank you for implement this great feature.

**Comment by coding-cucumber** [comment]
@lujjjh The rebooting issue was probably just a bug on my Mac specifically.
