### ISSUE TITLE
Different scroll step in different apps

### ISSUE THREAD

**Issue by RazrFalcon** [lujjjh/LinearMouse#16]
Thanks for the app, but I'm experiencing a variable scroll step size in different apps. I'm using the default 3 lines per scroll and it works just fine in the most apps, except that in Chromium-based apps (Chrome/VSCode) the step is 6, while in XCode and IDEA the step is 1.5

In some cases it has different step in the same app. Scrolling the code in XCode is 1.5 for me, but scrolling project files in XCode is 3. I have no idea why it acts like this.

I've also compared it with [MOS](https://github.com/Caldis/Mos) and it produces the fixed 3 lines per scroll in all the named apps. On the other hand, it use 6 lines step in other apps, like Terminal. Also, it feels like it uses something like 3.2-3.5 step.

PS: I did restart the mac after installing the app. I'm running mac 11.5.2 and LinearMouse 0.2.7

**Comment by lujjjh** [comment]
Yes, this is a known issue, but I haven't find any good solutions...

I've also tried [SteerMouse](https://plentycom.jp/en/steermouse/), which behaves the same as LinearMouse. I'm not sure how MOS works, but I'm guessing it scrolls in pixels rather than lines as it implements smooth scrolling.

**Comment by chrisequalsdev** [comment]
I can't use this app alongside 'Logitech Options' https://support.logi.com/hc/en-us/articles/360024842673--Downloads-M330-SILENT-PLUS for my M330 mouse. Without that software, my scroll wheel barely moves in some cases where there is a window within another one (example editing markdown on github in Chrome). With Logitech Options installed, I get the default scroll wheel acceleration and LinearMouse app doesn't have any affect.

**Comment by lujjjh** [comment]
> I can't use this app alongside 'Logitech Options' https://support.logi.com/hc/en-us/articles/360024842673--Downloads-M330-SILENT-PLUS for my M330 mouse. Without that software, my scroll wheel barely moves in some cases where there is a window within another one (example editing markdown on github in Chrome). With Logitech Options installed, I get the default scroll wheel acceleration and LinearMouse app doesn't have any affect.

Thanks for your feedback!

I have no M330 mouse so I couldn't have a test. But I also use Logitech Options for my ERGO M575 mouse and it works well.

Is it just scroll acceleration that isn't working, or are all of the other features (such as scroll reverse) broken as well? Are there any options for tweaking the mouse wheel in your Logitech Options?

BTW, instead of commenting here, you could open a new issue.

**Comment by podfishapp** [comment]
Any news on this?
