### ISSUE TITLE
Universal back + forth breaks mouse clicks in IntelliJ

### ISSUE THREAD

**Issue by ryantargz** [lujjjh/LinearMouse#19]
I have an interesting issue I was able to temporarily resolve, but wanted to bring to your attention @lujjjh 

When using intelliJ (Java development IDE) I was losing the ability to right or left click on anything within the window. At first it was seemingly random, but after lots of trial and error I came to the conclusion that it was after I had enabled "universal back and forth" from your latest update and had used either of my back/forth mouse buttons within intelliJ. The only solution to get clicks working again was restart my system completely, until eventually I turned off the universal back/forth feature and restarted which completely solved the problem.

I reproduced the issue across two systems. One was a 14" Macbook Pro M1 Max on macOS Monterey and the other was an Intel i9 9900k hackintosh running Big Sur.

I was doing some research into this and found a post in the intelliJ forums that may be of interest to you:
https://youtrack.jetbrains.com/issue/JBR-563#focus=Comments-27-3889722.0-0

Would love to see this fixed if possible -- not sure what the difference in functionality is, but BetterTouchTool seems to handle universal back/forth pretty well, I'm using that in the meantime. To accomplish it in BetterTouchTool, I have Mouse Button 3 bound to "3 Finger Swipe Left (Page Back)" and Mouse Button 4 bound to "3 Finger Swipe Right (Page Forward)".

**Comment by lujjjh** [comment]
Thank you for reporting this issue! I'll release a new version to fix it.

**Comment by lujjjh** [comment]
You could try [v0.2.8](https://github.com/lujjjh/LinearMouse/releases/tag/v0.2.8) and see if it works.

**Comment by ryantargz** [comment]
Awesome! Will try later today and report back!

**Comment by ryantargz** [comment]
Sorry for the delay, the fix seems to be working! Thanks again!
