### ISSUE TITLE
Launch on boot

### ISSUE THREAD

**Issue by JulianEggers** [lujjjh/LinearMouse#24]
Rebooting MacOs causes LinearMouse to be not launched again. Currently, I always have to manually relaunch the app.
Can this option be added to the LinearMouse settings?

**Comment by lujjjh** [comment]
LinearMouse should add itself into the login items automatically and remove itself only when it is manually quit by users.

Could you open System Preference -> Users and Groups -> Login Items and check if LinearMouse is in that list after launch?

<img src="https://user-images.githubusercontent.com/3000535/143848478-d341994b-b412-48db-940e-4a555dd2c000.png" width="780">

**Comment by JulianEggers** [comment]
I didn't know about these settings - thanks.
For me, LinearMouse was not listed there. (Could potentially be due to organization restrictions on the mac book.)
