### ISSUE TITLE
Optimized for M1?

### ISSUE THREAD

**Issue by BE-CH** [lujjjh/LinearMouse#25]
Great application! Really good job on all the features and simplicity. Keep up the good work.

Is LinearMouse optimized for M1? :)

**Comment by lujjjh** [comment]
Although not tested on M1, the releases are universal binaries, which means LinearMouse should run natively on M1 without the help of Rosetta transpiler. It would be nice if someone could verify it on M1 :)

**Comment by Reshurum** [comment]
I can confirm it's working fine on my M1 machine. Thank you so much for this program!

**Comment by ehhthing** [comment]
Can also confirm it's working on my M1 Pro machine. This app is amazing, thanks a lot!

**Comment by lujjjh** [comment]
@Reshurum @ehhthing Thank you very much. So I'm closing this issue. Please feel free to re-open it if performance issues on M1 are observed.
