### ISSUE TITLE
Slow trackpad scrolling while running LinearMouse

### ISSUE THREAD

**Issue by collinkreutzer** [lujjjh/LinearMouse#28]
Thanks for the wonderful app in the first place, it finally replaced SteerMouse for me. But I just noticed some weird behavior while using my trackpad after a long time of only using my mouse. The scrolling speed is severely slowed down while scrolling slowly. This happens while all options in LinearMouse are disabled but is back to normal as soon as I quit LinearMouse so it has to be related.

Is it just me or can someone else confirm this behavior? Running macOS Monterey 12.0.1 on a 14" MacBook Pro.

Edit: This seems to be caused by the most recent release introducing sensitivity/acceleration settings. I cannot reproduce this on 0.2.8.

**Comment by lujjjh** [comment]
Thank you! Should have been fixed in https://github.com/lujjjh/LinearMouse/actions/runs/1561763028.
