### ISSUE TITLE
Scroll Modifier

### ISSUE THREAD

**Issue by ryantargz** [lujjjh/LinearMouse#9]
I would love the ability to hold a modifier key, e.g. shift, and be able to scroll at a faster rate. This is great for viewing content that's formatted small or if you want to quickly reach the top of the page.

**Comment by lujjjh** [comment]
That's really cool. The only thing is that it may conflict with the default behaviors; for example, holding shift while scrolling alters the scrolling orientation from vertical to horizontal or vice versa. But, anyway, it would be great if this is configurable.

**Comment by ryantargz** [comment]
@lujjjh after v0.2.6, opening the LinearMouse Preferences panel does this:

![Screen Shot 2021-07-29 at 8 27 17 PM](https://user-images.githubusercontent.com/896146/127595752-7adeb425-5c39-4cd7-bc62-743f6064d8d7.png)

**Comment by lujjjh** [comment]
> @lujjjh after v0.2.6, opening the LinearMouse Preferences panel does this:
> 
> ![Screen Shot 2021-07-29 at 8 27 17 PM](https://user-images.githubusercontent.com/896146/127595752-7adeb425-5c39-4cd7-bc62-743f6064d8d7.png)

Could you tell me what version of macOS you're using?

**Comment by ryantargz** [comment]
macOS Catalina
Version 10.15.7

**Comment by lujjjh** [comment]
I reproduced it on Catalina.

**Comment by lujjjh** [comment]
@ryantargz I've also fixed some other Catalina compatibility issues and re-uploaded v0.2.6. Please [re-download v0.2.6](https://github.com/lujjjh/LinearMouse/releases/download/v0.2.6/LinearMouse.dmg) and try it again. Thank you.

**Comment by ryantargz** [comment]
> @ryantargz I've also fixed some other Catalina compatibility issues and re-uploaded v0.2.6. Please [re-download v0.2.6](https://github.com/lujjjh/LinearMouse/releases/download/v0.2.6/LinearMouse.dmg) and try it again. Thank you.

Works like a charm!
Also, I love that I can set more than one modifier key to "Change Speed x5" and press them all down for hyper-speed.
Very cool. Thanks again!

**Comment by lujjjh** [comment]
You are quite welcome! I'm closing this issue and feel free to reopen it if you need further help.
